# Page settings
baseurl = "localhost:1313"
title = "Empleo Now"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Ivan Hueso"
  description = "Empleo Now Descripcion."
  email = "ivanhueso@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Empleo Now"
    work = "Acerca de Nosotros"
    testimonials = "Testimonios"
    services = "Nuestros Productos"
    about = "Que Ofrecemos?"
    contact = "Inscribase"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Unete a nuestro team de ventas"
    subtitle = 'Excelente oportunidad laboral en la Florida  <a href="#" data-nav-section="contact">¡Inscribase Hoy!</a><br>o LLamenos al <a href="#fh5co-contact" data-nav-section="contact">(786) 440-8077</a>  '

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Nuestra Mision"
    description = "Es brindar servicio personal y productos excepcionales para usted y su familia. Ofreciendole soluciones claras y faciles que brinden dinero en efectivo pagado directamente a usted cuando mas lo necesite!"
    url = "#"
    button = "Get In Touch"
    icon = "icon-flag"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Que Hacemos"
    description = "Nos encargamos de evaluar las necesidades reales de nuestros clientes para asi poder ofrecer el producto adecuado basado en su situacion para que cuenten con el mayor beneficio posible."
    url = "#"
    button = "Click Me"
    icon = "icon-question"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Construyendo relaciones"
    description = "Todos tienen diferentes necesidades de seguro. Llámenos hoy para una evaluación personalizada de negocios o individual y descubra cómo podemos ayudarlo a proteger lo que tanto le costó conseguir."
    url = "#"
    section="work"
    button = "Ver Imagenes"
    icon = "icon-globe"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Ver video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=pSQn7Kpqufc"


  # Work section
  [params.work]
    enable = true
    title = "Acerca de Nosotros"
    description = "Compañía internacional líder en Seguros abriendo mercado latino en la Florida busca profesionales con experiencia en ventas, con licencia 215 o 240. Si todavía no tienes alguna de estas licencias te ayudamos a sacarla en 2 semanas. Puestos disponibles en Miami y Brodward .Agentes y Gerentes Territoriales"

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonios"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Nuestros Productos"

    [[params.services.item]]
      title = "Ingresos"
      description = "<b>Protector de Ingresos</b><br> Lo ayudara a pagar los gastos de su diario vivir.<br><br><b>Sick Pay Plus</b><br> Le ayuda a pagar los gastos de su vida diaria cuando usted no pueda trabajar debido a in accidente y enfermedad."
      icon = "icon-wallet"

    [[params.services.item]]
      title = "Accidentes y enfermedades"
      description = "<b>Protector para Accidentes y Enfermedad</b><br> Lo ayudara a pagar los gastos por accidente y enfermedad.<br><br><b>Protector para Accidentes</b><br> Ambos lo protegen contra los gastos no medicos asociados con el tratamiento y la recuperacion de una enfermedad o un accidente."
      icon = "icon-fire"

    [[params.services.item]]
      title = "Estilo de Vida de la Familia"
      description = "<b>Protector de Vida Familiar</b><br>Protege a su familia ante un accidente o enfermedad.<br><br><b>Protector de Ventaja Dorada</b><br> Ambos protegen el estilo de vida de su familia con un beneficio en efectivo para los sobrevivientes."
      icon = "icon-people"

      [[params.services.item]]
      title = "Condiciones Criticas"
      description = "<b>Protector de Cancer</b><br>Ayuda a pagar los gastos medicos y no medicos asociados a determinados problemas de salud."
      icon = "icon-clock"

  # About section
  [params.about]
    enable = true
    title = "Que Ofrecemos"
    description = "Por ser una empresa lider the ofrecemos los siguientes beneficios"

    [[params.about.item]]
      description = "Entrenamiento pago"

      [[params.about.item]]
        description = "Apoyo y formacion integral"

    [[params.about.item]]
      description = "Bonos semanales"


      [[params.about.item]]
            description = "Salario para Managers"

    [[params.about.item]]
      description = "Desarrollo y crecimiento"

    [[params.about.item]]
      description = "Lenguaje Español (inglés plus)"

    [[params.about.item]]
      description = "Plan 401 (K)"

    [[params.about.item]]
      description = "Seguro de invalidez"
      [[params.about.item]]
        description = "Seguro de vida, dental y vision"


  # Counters section
  [params.counters]
    enable = true
    title = "Quienes somos"
    description = "Compania de seguros con varias sucursales a lo largo y lo ancho de América del Norte. A.M. Best, la calificación de seguros mas prestigiosa y reconocida, nos otorga la calificación A+(superior) y contamos con mas de 3 millones de pólizas de seguros complementarios vigentes en América del Norte, además, pagamos casi 1 millón de dólares por día hábil."

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Inscribase"
    description = "Si te consideras un líder y tienes experiencia en ventas, regístrate aqui y nos comunicaremos a la brevedad para una entrevista."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5400 S University Dr <br>Davie, FL 3314 <br> United States"],
        ["icon-phone", "(786) 440-8077"],
        ["icon-envelope", "monica@empleonow.com"]
      ]

    name = "Nombre Completo"
    email = "Correo Electronico"
    phone = "Telefono"
    message = "Mensaje"
    button = "Inscribirme"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Copyright 2017-2018 Empleo Now. Todos los derechos reservados'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
