# Page settings
baseurl = "http://www.empleonow.com/"
title = "Empleo Now"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  # Meta
  author = "Ivan Hueso"
  description = "Unete a nuestro team de ventas. Excelente oportunidad laboral"
  email = "monica@empleonow.com"
  api_key = '880bca7a987d2eed486fef922a732ec2'
  # Navigation
  [params.navigation]
    brand = "Empleo Now"
    work = "Propuesta Laboral"
    testimonials = "Testimonios"
    services = "Nuestros Productos"
    about = "Que Ofrecemos?"
    contact = "Contáctese"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Unete a nuestro team de ventas"
    subtitle = 'Excelente oportunidad laboral  <a href="#fh5co-contact" data-nav-section="contact">¡Inscribase Hoy!</a><br>o LLamenos para una entrevista al <a href="#fh5co-contact" data-nav-section="contact">(786) 440-8077</a>'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Nuestra Mision"
    description = "Es brindar servicio personal y productos excepcionales para usted y su familia. Ofreciendole soluciones claras y faciles que brinden dinero en efectivo pagado directamente a usted cuando mas lo necesite!"
    url = "#"
    button = "Get In Touch"
    icon = "icon-flag"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Que Hacemos"
    description = "Nos encargamos de evaluar las necesidades reales de nuestros clientes para asi poder ofrecer el producto adecuado basado en su situacion para que cuenten con el mayor beneficio posible."
    url = "#"
    button = "Click Me"
    icon = "icon-question"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Construyendo relaciones"
    description = "Todos tienen diferentes necesidades de seguro. Llámenos hoy para una evaluación personalizada de negocios o individual y descubra cómo podemos ayudarlo a proteger lo que tanto le costó conseguir."
    url = "#"
    section="work"
    button = "Ver Imagenes"
    icon = "icon-globe"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Ver video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=pSQn7Kpqufc"


  # Work section
  [params.work]
    enable = true
    title = "Propuesta Laboral"
    description = "Compania internacional líder en Seguros, busca personas emprendedoras con experiencia en ventas. Requisitos Licencia 215 o 240 .(si todavía no tienes alguna de estas licencias te ayudamos a sacarla). Permiso para poder trabajar en USA. Disponibilidad de vehiculo. Puestos disponibles como Agentes y Gerentes Territoriales."

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonios"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;En esta compañía estamos en proceso de crecimiento esto implica para mi un ambiente de trabajo estimulante, dinámico, con mucha energía y lleno de oportunidades&rdquo;"
      person = 'Maria Velazquez'
      img = "person1.png"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Trabajo en esta Compania solida acumulando éxitos años tras años en la industria de seguros y principalmente con diversidad laboral , qué pasa a ser un Estilo de Vida para mi&rdquo;"
      person = 'Gerardo De Leon'
      img = "person2.png"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Estoy tarabajando en esta Compania hace 5 años y ha sido de constante Capacitacion, Crecimiento personal , profesional y económico&rdquo;"
      person = 'Giselle Martinez'
      img = "person3.png"
      alt = "Person3"


  # Services section
  [params.services]
    enable = true
    title = "Nuestros Productos"

    [[params.services.item]]
      title = "Ingresos"
      description = "<b>Protector de Ingresos</b><br> Lo ayudara a pagar los gastos de su vida diaria.<br><br><b>Sick Pay Plus</b><br> Le ayuda a pagar los gastos de su vida diaria cuando usted no pueda trabajar debido a un accidente o enfermedad."
      icon = "icon-wallet"

    [[params.services.item]]
      title = "Accidentes y enfermedades"
      description = "<b>Protector para Accidentes y Enfermedad</b><br> Lo ayudara a pagar los gastos por accidente y enfermedad en una hospitalización.<br><br><b>Protector para Accidentes</b><br> Lo ayudara a pagar los gastos por accidente en una hospitalización."
      icon = "icon-fire"

    [[params.services.item]]
      title = "Estilo de Vida de la Familia"
      description = "<b>Protector de Vida Familiar</b><br>Protege a su familia en case de fallecimiento.<br><br><b>Protector de Ventaja Dorada</b><br> Ayuda a su familia en caso de perdida de vida."
      icon = "icon-people"

      [[params.services.item]]
      title = "Condiciones Criticas"
      description = "<b>Protector de Cancer</b><br>Ayuda a pagar los gastos de hospitalización."
      icon = "icon-clock"

  # About section
  [params.about]
    enable = true
    title = "Que Ofrecemos?"
    description = "Por ser una empresa lider le ofrecemos los siguientes beneficios"

    [[params.about.item]]
      description = "Entrenamiento pago"

      [[params.about.item]]
        description = "Apoyo y formacion integral"

    [[params.about.item]]
      description = "Bonos semanales"

    [[params.about.item]]
            description = "Salario para Managers"

    [[params.about.item]]
      description = "Desarrollo y crecimiento"

    [[params.about.item]]
      description = "Lenguaje Español (inglés plus)"

    [[params.about.item]]
      description = "Plan 401 (K)"

    [[params.about.item]]
      description = "Seguro de invalidez"
      [[params.about.item]]
        description = "Seguro de vida, dental y vision"


  # Counters section
  [params.counters]
    enable = true
    title = "Quienes somos"
    description = "Compañia de seguros con varias sucursales a lo largo y lo ancho de América del Norte. A.M. Best, la calificación de seguros mas prestigiosa y reconocida, nos otorga la calificación A+(superior) y contamos con mas de 3 millones de pólizas de seguros complementarios vigentes en América del Norte, además, pagamos casi 1 millón de dólares por día hábil."

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contáctese"
    description = "Si te consideras un líder y tienes experiencia en ventas, regístrate aqui y nos comunicaremos a la brevedad para una entrevista."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5400 S University Dr <br>Davie, FL 33314 <br> United States"],
        ["icon-phone", "(786) 440-8077"],
        ["icon-envelope", "monica@empleonow.com"]
      ]

    name = "Nombre Completo"
    email = "Correo Electronico"
    phone = "Telefono"
    message = "Mensaje"
    button = "Inscribirme"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Copyright 2017-2018 Empleo Now. Todos los derechos reservados'
